#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: getInput (day number)" >&2
    exit 2
fi

directions="Please populate this file with the value of your "session" cookie from (inspect element->storage->cookies->https://adventofcode.com)"

if [ ! -f .session_id ]; then
    echo "Error: .session_id not found. ${directions}"
    exit 1
fi

curl -s -o input/day$1 --cookie session=$(<.session_id) https://adventofcode.com/2024/day/$1/input

if grep -q -F -x "Puzzle inputs differ by user.  Please log in to get your puzzle input." "input/day$1"; then
    echo "Error: invalid .session_id. ${directions}"
    rm input/day$1
    exit 1
fi

if grep -q -F -x "Please don't repeatedly request this endpoint before it unlocks! The calendar countdown is synchronized with the server time; the link will be enabled on the calendar the instant this puzzle becomes available." "input/day$1"; then
    echo "Error: Inputs for day $1 have not released yet!"
    rm input/day$1
    exit 1
fi

exit 0